namespace Hibana.Api;

using System.Collections.Concurrent;
using System.Globalization;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;

public sealed class WeatherOptions { public int MaximumHourlyHours { get; init; } = 168; public int MaximumDailyDays { get; init; } = 16; public int CurrentWeatherCacheMinutes { get; init; } = 10; public int ForecastCacheMinutes { get; init; } = 30; public int GeocodingCacheHours { get; init; } = 168; }
public sealed class ProviderOptions { public string BaseUrl { get; init; } = ""; public int TimeoutSeconds { get; init; } = 10; }
public sealed class ProviderUnavailableException : Exception { public ProviderUnavailableException() { } }
public sealed record WeatherQuery(double Latitude, double Longitude, int HourlyHours = 24, int DailyDays = 7, string Units = "metric");
public sealed record Coordinates(double Latitude, double Longitude);
public sealed record WeatherCondition(string Code, string Label, string IconKey, int? ProviderCode);
public sealed record LocationDescriptor(string Name, string? Region, string? Country, string? CountryCode, string DisplayName, string? Timezone, DateTimeOffset? LocalTime);
public sealed record Wind(double Speed, int DirectionDegrees, string Direction, double? GustSpeed);
public sealed record CurrentWeather(DateTimeOffset? ObservedAt, double Temperature, double FeelsLike, WeatherCondition Condition, int? HumidityPercent, double? Precipitation, double? Rain, double? Snowfall, int? CloudCoverPercent, double? Pressure, double? Visibility, Wind Wind, bool IsDay);
public sealed record SunTimes(DateTimeOffset? Sunrise, DateTimeOffset? Sunset);
public sealed record HourlyWeather(DateTimeOffset Time, double Temperature, WeatherCondition Condition, int? PrecipitationProbability, double? WindSpeed);
public sealed record DailyWeather(DateOnly Date, WeatherCondition Condition, double MinimumTemperature, double MaximumTemperature, int? PrecipitationProbability, DateTimeOffset? Sunrise, DateTimeOffset? Sunset);
public sealed record Units(string Temperature, string WindSpeed, string Precipitation, string Pressure, string Visibility);
public sealed record WeatherMetadata(string WeatherProvider, string LocationProvider, bool Cached, DateTimeOffset GeneratedAt);
public sealed record WeatherResponse(Coordinates Coordinates, LocationDescriptor Location, CurrentWeather Current, SunTimes Sun, IReadOnlyList<HourlyWeather> Hourly, IReadOnlyList<DailyWeather> Daily, Units Units, WeatherMetadata Metadata);
public sealed record SearchLocation(string Name, string? Region, string? Country, string? CountryCode, double Latitude, double Longitude, string? Timezone);
public interface IWeatherService { Task<WeatherResponse> GetWeatherAsync(WeatherQuery query, CancellationToken cancellationToken); }
public interface IWeatherProvider { Task<OpenMeteoResponse> GetAsync(double latitude, double longitude, WeatherQuery query, CancellationToken cancellationToken); }
public interface IReverseGeocodingProvider { Task<LocationDescriptor?> ReverseAsync(double latitude, double longitude, CancellationToken cancellationToken); Task<IReadOnlyList<SearchLocation>> SearchAsync(string query, CancellationToken cancellationToken); }
public interface ILocationService { Task<IReadOnlyList<SearchLocation>> SearchAsync(string query, CancellationToken cancellationToken); Task<LocationDescriptor?> ReverseAsync(double latitude, double longitude, CancellationToken cancellationToken); }

[ApiController, Route("api/v1/weather")]
public sealed class WeatherController(IWeatherService weatherService) : ControllerBase {
 [HttpGet] public async Task<ActionResult<WeatherResponse>> Get([FromQuery] double latitude, [FromQuery] double longitude, [FromQuery] int hourlyHours = 24, [FromQuery] int dailyDays = 7, [FromQuery] string units = "metric", CancellationToken cancellationToken = default) { if (latitude is < -90 or > 90 || longitude is < -180 or > 180 || hourlyHours is < 1 or > 168 || dailyDays is < 1 or > 16 || units is not ("metric" or "imperial")) return BadRequest(new ValidationProblemDetails(new Dictionary<string, string[]> { ["query"] = ["Latitude must be -90 through 90, longitude -180 through 180, hourlyHours 1 through 168, dailyDays 1 through 16, and units metric or imperial."] })); return Ok(await weatherService.GetWeatherAsync(new(latitude, longitude, hourlyHours, dailyDays, units), cancellationToken)); }
}
[ApiController, Route("api/v1/locations")]
public sealed class LocationsController(ILocationService locations) : ControllerBase {
 [HttpGet("search")] public async Task<ActionResult<IReadOnlyList<SearchLocation>>> Search([FromQuery] string query, CancellationToken cancellationToken) { if (string.IsNullOrWhiteSpace(query) || query.Trim().Length < 2) return BadRequest(new ValidationProblemDetails(new Dictionary<string,string[]> { ["query"] = ["Query must contain at least 2 characters."] })); return Ok(await locations.SearchAsync(query.Trim(), cancellationToken)); }
 [HttpGet("reverse")] public async Task<ActionResult<LocationDescriptor>> Reverse([FromQuery] double latitude, [FromQuery] double longitude, CancellationToken cancellationToken) { if (latitude is < -90 or > 90 || longitude is < -180 or > 180) return BadRequest(new ValidationProblemDetails(new Dictionary<string,string[]> { ["coordinates"] = ["Latitude must be -90 through 90 and longitude -180 through 180."] })); var location = await locations.ReverseAsync(latitude, longitude, cancellationToken); return location is null ? NotFound() : Ok(location); }
}

public sealed class WeatherService(IWeatherProvider weatherProvider, IReverseGeocodingProvider locationProvider, IMemoryCache cache, IOptions<WeatherOptions> options, ILogger<WeatherService> logger) : IWeatherService {
 private static readonly ConcurrentDictionary<string, SemaphoreSlim> Locks = new();
 public async Task<WeatherResponse> GetWeatherAsync(WeatherQuery query, CancellationToken cancellationToken) { var lat = Math.Round(query.Latitude, 3); var lon = Math.Round(query.Longitude, 3); var key = $"weather:{lat:F3}:{lon:F3}:{query.Units}:{query.HourlyHours}:{query.DailyDays}"; if (cache.TryGetValue<WeatherResponse>(key, out var cached)) return cached! with { Metadata = cached!.Metadata with { Cached = true } }; var gate = Locks.GetOrAdd(key, _ => new SemaphoreSlim(1,1)); await gate.WaitAsync(cancellationToken); try { if (cache.TryGetValue<WeatherResponse>(key, out cached)) return cached! with { Metadata = cached!.Metadata with { Cached = true } }; var rawTask = weatherProvider.GetAsync(lat, lon, query, cancellationToken); var locationTask = locationProvider.ReverseAsync(lat, lon, cancellationToken); await Task.WhenAll(rawTask, locationTask.ContinueWith(_ => { }, CancellationToken.None)); var raw = await rawTask; var location = locationTask.IsCompletedSuccessfully && locationTask.Result is { } resolved ? resolved : FallbackLocation(lat, lon, raw.Timezone); var response = Map(raw, location, query.Units); cache.Set(key, response, TimeSpan.FromMinutes(options.Value.ForecastCacheMinutes)); logger.LogInformation("Weather fetched for {Latitude}, {Longitude}; cache miss", lat, lon); return response; } finally { gate.Release(); Locks.TryRemove(key, out _); } }
 private static LocationDescriptor FallbackLocation(double lat, double lon, string? timezone) => new($"{Math.Abs(lat):F4}° {(lat < 0 ? "S" : "N")}, {Math.Abs(lon):F4}° {(lon < 0 ? "W" : "E")}", null, null, null, $"{Math.Abs(lat):F4}° {(lat < 0 ? "S" : "N")}, {Math.Abs(lon):F4}° {(lon < 0 ? "W" : "E")}", timezone, null);
 private static WeatherResponse Map(OpenMeteoResponse raw, LocationDescriptor location, string requestedUnits) { var zone = TimeZoneInfo.FindSystemTimeZoneById(raw.Timezone ?? "UTC"); DateTimeOffset Convert(string? value) => value is null ? default : new DateTimeOffset(DateTime.SpecifyKind(DateTime.Parse(value, CultureInfo.InvariantCulture), DateTimeKind.Unspecified), zone.GetUtcOffset(DateTime.Parse(value, CultureInfo.InvariantCulture))); var current = raw.Current ?? new(); var h = raw.Hourly ?? new(); var d = raw.Daily ?? new(); var time = Convert(current.Time); var loc = location with { Timezone = raw.Timezone ?? location.Timezone, LocalTime = time == default ? null : time }; var temperatureUnit = requestedUnits == "imperial" ? "fahrenheit" : "celsius"; return new(new(raw.Latitude, raw.Longitude), loc, new(time == default ? null : time, current.Temperature2m ?? 0, current.ApparentTemperature ?? 0, Condition(current.WeatherCode), current.RelativeHumidity2m, current.Precipitation, current.Rain, current.Snowfall, current.CloudCover, current.SurfacePressure, current.Visibility, new(current.WindSpeed10m ?? 0, (int)(current.WindDirection10m ?? 0), WindDirection(current.WindDirection10m ?? 0), current.WindGusts10m), current.IsDay == 1), new(d.Sunrise?.FirstOrDefault() is { } sunrise ? Convert(sunrise) : null, d.Sunset?.FirstOrDefault() is { } sunset ? Convert(sunset) : null), h.Time?.Select((x,i) => new HourlyWeather(Convert(x), h.Temperature2m?.ElementAtOrDefault(i) ?? 0, Condition(h.WeatherCode?.ElementAtOrDefault(i)), h.PrecipitationProbability?.ElementAtOrDefault(i), h.WindSpeed10m?.ElementAtOrDefault(i))).ToList() ?? [], d.Time?.Select((x,i) => new DailyWeather(DateOnly.Parse(x), Condition(d.WeatherCode?.ElementAtOrDefault(i)), d.Temperature2mMin?.ElementAtOrDefault(i) ?? 0, d.Temperature2mMax?.ElementAtOrDefault(i) ?? 0, d.PrecipitationProbabilityMax?.ElementAtOrDefault(i), d.Sunrise?.ElementAtOrDefault(i) is { } sr ? Convert(sr) : null, d.Sunset?.ElementAtOrDefault(i) is { } ss ? Convert(ss) : null)).ToList() ?? [], new(temperatureUnit, requestedUnits == "imperial" ? "mph" : "km/h", requestedUnits == "imperial" ? "in" : "mm", "hPa", "m"), new("Open-Meteo", "OpenStreetMap Nominatim", false, DateTimeOffset.UtcNow)); }
 internal static WeatherCondition Condition(int? code) => code switch { 0 => new("clear","Clear sky","clear",code), 1 => new("mostly-clear","Mostly clear","mostly-clear",code), 2 => new("partly-cloudy","Partly cloudy","partly-cloudy",code), 3 => new("overcast","Overcast","overcast",code), 45 or 48 => new("fog","Fog","fog",code), >= 51 and <= 57 => new("drizzle","Drizzle","drizzle",code), >= 61 and <= 67 or >= 80 and <= 82 => new("rain","Rain","rain",code), >= 71 and <= 77 or >= 85 and <= 86 => new("snow","Snow","snow",code), >= 95 and <= 99 => new("thunderstorm","Thunderstorm","thunderstorm",code), _ => new("unknown","Unknown","unknown",code) };
 internal static string WindDirection(double degrees) => new[]{"N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"}[(int)Math.Round(degrees / 22.5, MidpointRounding.AwayFromZero) % 16];
}

public sealed class OpenMeteoWeatherProvider(HttpClient client) : IWeatherProvider { public async Task<OpenMeteoResponse> GetAsync(double lat, double lon, WeatherQuery query, CancellationToken cancellationToken) { var units = query.Units == "imperial" ? "&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch" : ""; var path = $"/v1/forecast?latitude={lat.ToString(CultureInfo.InvariantCulture)}&longitude={lon.ToString(CultureInfo.InvariantCulture)}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,precipitation,rain,snowfall,cloud_cover,surface_pressure,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day&hourly=temperature_2m,weather_code,precipitation_probability,wind_speed_10m&daily=weather_code,temperature_2m_min,temperature_2m_max,precipitation_probability_max,sunrise,sunset&forecast_days={query.DailyDays}&timezone=auto{units}"; using var response = await client.GetAsync(path, cancellationToken); if (!response.IsSuccessStatusCode) throw new ProviderUnavailableException(); return await response.Content.ReadFromJsonAsync<OpenMeteoResponse>(cancellationToken: cancellationToken) ?? throw new ProviderUnavailableException(); } }
public sealed class NominatimLocationProvider(HttpClient client, IMemoryCache cache) : IReverseGeocodingProvider { public async Task<LocationDescriptor?> ReverseAsync(double lat, double lon, CancellationToken cancellationToken) { var key=$"reverse:{lat:F3}:{lon:F3}"; if(cache.TryGetValue<LocationDescriptor>(key,out var result)) return result; try { using var response=await client.GetAsync($"/reverse?format=jsonv2&lat={lat.ToString(CultureInfo.InvariantCulture)}&lon={lon.ToString(CultureInfo.InvariantCulture)}&zoom=10",cancellationToken); if(!response.IsSuccessStatusCode)return null; var dto=await response.Content.ReadFromJsonAsync<NominatimReverse>(cancellationToken:cancellationToken); var address=dto?.Address; if(address is null)return null; var name=address.City??address.Town??address.Village??address.County??"Selected location"; result=new(name,address.State,address.Country,address.CountryCode?.ToUpperInvariant(),string.Join(", ",new[]{name,address.State,address.Country}.Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct()),null,null); cache.Set(key,result,TimeSpan.FromDays(7)); return result; } catch(HttpRequestException){return null;} }
 public async Task<IReadOnlyList<SearchLocation>> SearchAsync(string query, CancellationToken cancellationToken) { var key="search:"+query.ToLowerInvariant(); if(cache.TryGetValue<IReadOnlyList<SearchLocation>>(key,out var cached))return cached!; using var response=await client.GetAsync($"/search?format=jsonv2&addressdetails=1&limit=6&q={Uri.EscapeDataString(query)}",cancellationToken); if(!response.IsSuccessStatusCode)throw new ProviderUnavailableException(); var values=await response.Content.ReadFromJsonAsync<List<NominatimSearch>>(cancellationToken:cancellationToken)??[]; var result=values.Select(x=>new SearchLocation(x.Name??x.DisplayName??"Selected location",x.Address?.State,x.Address?.Country,x.Address?.CountryCode?.ToUpperInvariant(),double.Parse(x.Latitude,CultureInfo.InvariantCulture),double.Parse(x.Longitude,CultureInfo.InvariantCulture),null)).ToList(); cache.Set(key,result,TimeSpan.FromHours(6));return result; } }
public sealed class LocationService(IReverseGeocodingProvider provider) : ILocationService { public Task<IReadOnlyList<SearchLocation>> SearchAsync(string query,CancellationToken cancellationToken)=>provider.SearchAsync(query,cancellationToken); public Task<LocationDescriptor?> ReverseAsync(double latitude,double longitude,CancellationToken cancellationToken)=>provider.ReverseAsync(latitude,longitude,cancellationToken); }
public sealed class OpenMeteoResponse { public double Latitude {get;set;} public double Longitude {get;set;} public string? Timezone {get;set;} public OpenMeteoCurrent? Current {get;set;} public OpenMeteoHourly? Hourly {get;set;} public OpenMeteoDaily? Daily {get;set;} }
public sealed class OpenMeteoCurrent { public string? Time {get;set;} [JsonPropertyName("temperature_2m")] public double? Temperature2m {get;set;} [JsonPropertyName("apparent_temperature")] public double? ApparentTemperature {get;set;} [JsonPropertyName("relative_humidity_2m")] public int? RelativeHumidity2m {get;set;} [JsonPropertyName("weather_code")] public int? WeatherCode {get;set;} public double? Precipitation {get;set;} public double? Rain {get;set;} public double? Snowfall {get;set;} [JsonPropertyName("cloud_cover")] public int? CloudCover {get;set;} [JsonPropertyName("surface_pressure")] public double? SurfacePressure {get;set;} public double? Visibility {get;set;} [JsonPropertyName("wind_speed_10m")] public double? WindSpeed10m {get;set;} [JsonPropertyName("wind_direction_10m")] public double? WindDirection10m {get;set;} [JsonPropertyName("wind_gusts_10m")] public double? WindGusts10m {get;set;} [JsonPropertyName("is_day")] public int? IsDay {get;set;} }
public sealed class OpenMeteoHourly { public List<string>? Time {get;set;} [JsonPropertyName("temperature_2m")] public List<double>? Temperature2m {get;set;} [JsonPropertyName("weather_code")] public List<int?>? WeatherCode {get;set;} [JsonPropertyName("precipitation_probability")] public List<int?>? PrecipitationProbability {get;set;} [JsonPropertyName("wind_speed_10m")] public List<double?>? WindSpeed10m {get;set;} }
public sealed class OpenMeteoDaily { public List<string>? Time {get;set;} [JsonPropertyName("weather_code")] public List<int?>? WeatherCode {get;set;} [JsonPropertyName("temperature_2m_min")] public List<double>? Temperature2mMin {get;set;} [JsonPropertyName("temperature_2m_max")] public List<double>? Temperature2mMax {get;set;} [JsonPropertyName("precipitation_probability_max")] public List<int?>? PrecipitationProbabilityMax {get;set;} public List<string>? Sunrise {get;set;} public List<string>? Sunset {get;set;} }
public sealed class NominatimReverse { public NominatimAddress? Address {get;set;} }
public sealed class NominatimSearch { [JsonPropertyName("name")] public string? Name {get;set;} [JsonPropertyName("display_name")] public string? DisplayName {get;set;} [JsonPropertyName("lat")] public string Latitude {get;set;}="0"; [JsonPropertyName("lon")] public string Longitude {get;set;}="0"; public NominatimAddress? Address {get;set;} }
public sealed class NominatimAddress { public string? City {get;set;} public string? Town {get;set;} public string? Village {get;set;} public string? County {get;set;} public string? State {get;set;} public string? Country {get;set;} [JsonPropertyName("country_code")] public string? CountryCode {get;set;} }
